# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Submit a new Production build to Crashlytics Beta"
  lane :beta do |options|
    begin
      crashlytics(
        notes_path: "fastlane/changelog.txt",
        notifications: true,
        apk_path: "../build/app/outputs/apk/release/app-release.apk",
        api_token: options[:CRASHLYTICS_TOKEN],
        build_secret: options[:CRASHLYTICS_SECRET],
        emails: options[:CRASHLYTICS_EMAILS]
      )
      slack(
        username: "Fastlane - LiuLo",
        message: "A new Production build was successfully released!",
        channel: options[:SLACK_CHANNEL],
        slack_url: options[:SLACK_URL],
      )
    rescue => exception
      slack(
        username: "Fastlane - LiuLo",
        message: "Oops! Something went wrong with Production build!",
        channel: options[:SLACK_CHANNEL],
        slack_url: options[:SLACK_URL],
        success: false,
        attachment_properties: {
          fields: [
            {
              title: "Error message",
              value: exception.to_s,
              short: true
            }
          ]
        }
      )
    end
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    begin
      upload_to_play_store(
        apk: "../build/app/outputs/apk/release/app-release.apk",
      )
      slack(
        username: "Fastlane - LiuLo",
        message: "A new Production build was successfully uploaded to Google Play Store!",
        channel: options[:SLACK_CHANNEL],
        slack_url: options[:SLACK_URL],
      )
    rescue => exception
      slack(
        username: "Fastlane - LiuLo",
        message: "Oops! Something went wrong with Google Play Store deployment!",
        channel: options[:SLACK_CHANNEL],
        slack_url: options[:SLACK_URL],
        success: false,
        attachment_properties: {
          fields: [
            {
              title: "Error message",
              value: exception.to_s,
              short: true
            }
          ]
        }
      )
    end
  end

end
